[theme]
primaryColor="#9AB793"
backgroundColor = "#222834"
secondaryBackgroundColor="#333C4E"
textColor="#E5E8EE"
font="sans serif"

[server]
headless = true
enableStaticServing = true
#port = 443
#sslCertFile = '/path/to/certfile.crt'
#sslKeyFile = '/path/to/keyfile.key'

[browser]
#serverAddress = "ttoirl.it.ntnu.no"
gatherUsageStats = false

[logger]
level = "info"
